version: "3"

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    restart: always
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./log:/opt/teamcity/logs
    ports:
     - "8111:8111"
 