version: "2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      #- "4369:4369"
      #- "5671:5671"
      #- "5672:5672"
      #- "25672:25672"
      - "15672:15672"
 
