version: "2"

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./config:/etc/mysql
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc
    ports:
     - "127.0.0.1:3306:3306"
    container_name: mysql_main
 
