version: '2'
 
services:
   mysql:
     image: mysql:5.7
     volumes:
       - $PWD/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: youpwd
 
   discuz:
     depends_on:
       - mysql
     image: skyzhou/docker-discuz
     ports:
       - "8080:80"
     restart: always